#!/usr/bin/env node
// Generates docs/REFERENCE.md from the registries (params, machines, pages,
// commands, presets). Run after changing src/core/params.js or commands.js:
//   node tools/describe.mjs          (writes docs/REFERENCE.md)
//   node tools/describe.mjs --json   (prints machine-readable JSON)
//   node tools/describe.mjs --check  (exit 1 if docs/REFERENCE.md is stale; used by tests)

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { SOUND_PARAMS, FX_PARAMS, MACHINES, COMMON_PAGES, FX_PAGES, PAGE_ORDER, CONDITIONS, RETRIG_RATES, LENGTHS, SPEEDS, paramMachine } from '../src/core/params.js';
import { COMMANDS } from '../src/core/commands.js';
import { PRESETS } from '../src/core/presets.js';

if (process.argv.includes('--json')) {
  console.log(JSON.stringify({ commands: COMMANDS, machines: MACHINES, commonPages: COMMON_PAGES, fxPages: FX_PAGES, soundParams: SOUND_PARAMS, fxParams: FX_PARAMS, conditions: CONDITIONS, presets: PRESETS.map((p) => p.name) }, null, 1));
  process.exit(0);
}

const esc = (s) => String(s).replace(/\|/g, '\\|');
const range = (p) => (p.type === 'enum' ? p.options.join(' / ') : p.type === 'bool' ? 'true / false' : p.type === 'dest' ? "'none' or a modulatable param id" : `${p.min} … ${p.max}${p.int ? ' (int)' : ''}`);
const row = (p) => `| \`${p.id}\` | ${p.label} | ${p.name} | ${esc(range(p))} | ${JSON.stringify(p.def)} | ${p.lock ? '✓' : ''} | ${p.mod ? '✓' : ''} |`;
const head = '| id | label | name | range | default | lock | LFO |\n|---|---|---|---|---|---|---|';
const pageOf = {};
for (const [pg, ids] of Object.entries(COMMON_PAGES)) ids.forEach((id, i) => id && (pageOf[id] = `${pg}:${'ABCDEFGH'[i]}`));
for (const m of Object.values(MACHINES)) for (const [pg, ids] of Object.entries(m.pages)) ids.forEach((id, i) => id && (pageOf[id] = `${pg}:${'ABCDEFGH'[i]}`));

let md = `# DIGITONE//WEB reference (generated)

> Generated by \`node tools/describe.mjs\` from \`src/core/params.js\`, \`src/core/commands.js\`, \`src/core/presets.js\`. Do not edit by hand.

## Commands (reducer)

| type | args | description |
|---|---|---|
${Object.entries(COMMANDS).map(([k, v]) => `| \`${k}\` | \`${esc(v.args)}\` | ${esc(v.doc)} |`).join('\n')}

Every command also accepts \`pattern: "B03"\` to target a pattern other than the current one.

## Page layout

Pages: ${PAGE_ORDER.join(', ')} (SYN3 only for machines that define it). Slots A–H map to the 8 encoders.

| page | ${'ABCDEFGH'.split('').join(' | ')} |
|---|${'---|'.repeat(8)}
${Object.entries(COMMON_PAGES).map(([pg, ids]) => `| ${pg} | ${ids.map((i) => (i ? `\`${i}\`` : '—')).join(' | ')} |`).join('\n')}
${Object.values(MACHINES).flatMap((m) => Object.entries(m.pages).map(([pg, ids]) => `| ${m.id} ${pg} | ${ids.map((i) => (i ? `\`${i}\`` : '—')).join(' | ')} |`)).join('\n')}

## Machines

${Object.values(MACHINES).map((m) => `- **${m.name}** (\`${m.id}\`): ${m.about}`).join('\n')}

## Sound parameters

Common to every machine:

${head}
${SOUND_PARAMS.filter((p) => !paramMachine(p.id)).map(row).join('\n')}

${Object.values(MACHINES).map((m) => `### ${m.name} (\`${m.id}\`)\n\n${head}\n${SOUND_PARAMS.filter((p) => paramMachine(p.id) === m.id).map(row).join('\n')}`).join('\n\n')}

## Kit FX parameters (\`setFx\`)

${head}
${FX_PARAMS.map(row).join('\n')}

## Sequencer vocabularies

- Trig conditions: ${CONDITIONS.map((c) => `\`${c}\``).join(' ')}
- Retrig rates: ${RETRIG_RATES.join(', ')} (1/16 = one step)
- Lengths (steps): ${LENGTHS.join(', ')}
- Speeds: ${SPEEDS.join(', ')}

## Factory presets

${PRESETS.map((p) => `- \`${p.name}\` — ${MACHINES[p.machine].name}, ${p.category}`).join('\n')}
`;
void pageOf;
const out = new URL('../docs/REFERENCE.md', import.meta.url);
if (process.argv.includes('--check')) {
  const cur = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (cur !== md) { console.error('docs/REFERENCE.md is stale — run: node tools/describe.mjs'); process.exit(1); }
  console.log('docs/REFERENCE.md is up to date');
  process.exit(0);
}
mkdirSync(new URL('../docs/', import.meta.url), { recursive: true });
writeFileSync(new URL('../docs/REFERENCE.md', import.meta.url), md);
console.log('wrote docs/REFERENCE.md');
